-- DROP TABLE IF EXISTS `grafica`.`cliente`, `grafica`.`material`, `grafica`.`material_product`, `grafica`.`product`, `grafica`.`provider`, `grafica`.`purchases`, `grafica`.`purchases_material`, `grafica`.`quote`;
-- DROP TABLE IF EXISTS `grafica`.`cliente`, `grafica`.`material`, `grafica`.`material_product`, `grafica`.`product`, `grafica`.`provider`, `grafica`.`purchases`, `grafica`.`purchases_material`, `grafica`.`quote`;
-- DROP TABLE IF EXISTS `grafica`.`cliente`, `grafica`.`material`, `grafica`.`material_product`, `grafica`.`product`, `grafica`.`provider`, `grafica`.`purchases`, `grafica`.`purchases_material`, `grafica`.`quote`;
-- DROP TABLE IF EXISTS `grafica`.`cliente`, `grafica`.`material`, `grafica`.`material_product`, `grafica`.`product`, `grafica`.`provider`, `grafica`.`purchases`, `grafica`.`purchases_material`, `grafica`.`quote`;


-- MySQL Script generated by MySQL Workbench
-- 10/30/16 17:55:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Grafica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Grafica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Grafica` DEFAULT CHARACTER SET utf8 ;
USE `Grafica` ;

-- -----------------------------------------------------
-- Table `Grafica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `lastname` VARCHAR(60) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(700) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`quote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`quote` (
  `cliente_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `price` DOUBLE NOT NULL,
  `time_response` BIGINT NULL,
  PRIMARY KEY (`cliente_id`, `product_id`, `date`),
  INDEX `fk_cliente_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_cliente_has_product_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_cliente_has_product_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Grafica`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Grafica`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`material` (
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `price` DOUBLE NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`material_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`material_product` (
  `product_id` INT NOT NULL,
  `material_name` VARCHAR(45) NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`product_id`, `material_name`),
  INDEX `fk_product_has_material_product1_idx` (`product_id` ASC),
  INDEX `fk_material_product_material1_idx` (`material_name` ASC),
  CONSTRAINT `fk_product_has_material_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Grafica`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_product_material1`
    FOREIGN KEY (`material_name`)
    REFERENCES `Grafica`.`material` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`provider` (
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`purchases` (
  `id_purchases` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `date` DATE NULL,
  `total_price` DOUBLE NULL,
  PRIMARY KEY (`id_purchases`, `provider_name`),
  INDEX `fk_purchases_provider1_idx` (`provider_name` ASC),
  CONSTRAINT `fk_purchases_provider1`
    FOREIGN KEY (`provider_name`)
    REFERENCES `Grafica`.`provider` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafica`.`purchases_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafica`.`purchases_material` (
  `purchases_id` INT NOT NULL,
  `material_name` VARCHAR(45) NOT NULL,
  `quantity` INT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`purchases_id`, `material_name`),
  INDEX `fk_purchases_has_material_purchases1_idx` (`purchases_id` ASC),
  INDEX `fk_purchases_material_material1_idx` (`material_name` ASC),
  CONSTRAINT `fk_purchases_has_material_purchases1`
    FOREIGN KEY (`purchases_id`)
    REFERENCES `Grafica`.`purchases` (`id_purchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchases_material_material1`
    FOREIGN KEY (`material_name`)
    REFERENCES `Grafica`.`material` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
